### PR TITLE
add timeout and bug fix

### PR DESCRIPTION
**Pull request by Witee**
Your program does not have a timeout mechanism, will be stuck in the establishment of socket.

### CODE REVIEW

**Comment by dnaeon** [comment]
Thanks for this PR!

One question - why pass the IOError exception?

Thanks!

**Comment by Witee** [comment]
Because this is timeout not error.

**Comment by Witee** [comment]
This is my case:
```
from core.py import Tracer

t = Tracer('1.1.1.1')
t.run()

```
If the IP of a route does not return information, your code has been waiting, I added a timeout, so the above is not a ERROR, but time out.

**Comment by dnaeon** [comment]
Cool,  thanks!

**Pull request merged**
